const Data = [
  { name: 'Cappuccino', price: 3.50, description: 'A classic Italian coffee drink made with espresso and steamed milk.', category: 'Coffee' },
  { name: 'Chocolate Cake', price: 5.99, description: 'Decadent chocolate cake topped with rich chocolate ganache.', category: 'Desserts' },
  { name: 'Club Sandwich', price: 8.99, description: 'A triple-decker sandwich with layers of turkey, bacon, lettuce, tomato, and mayo.', category: 'Lunch' },
  { name: 'Pancakes', price: 6.50, description: 'Fluffy pancakes served with maple syrup and butter.', category: 'Breakfast' },
  { name: 'Orange Juice', price: 2.00, description: 'Freshly squeezed orange juice.', category: 'Juice' },
  { name: 'Iced Tea', price: 1.99, description: 'Refreshing iced tea served with lemon wedges.', category: 'Drinks' },
  { name: 'Espresso', price: 2.00, description: 'A strong shot of Italian-style coffee.', category: 'Coffee' },
  { name: 'Cheesecake', price: 4.99, description: 'Creamy cheesecake topped with fruit compote.', category: 'Desserts' },
  { name: 'Caesar Salad', price: 7.50, description: 'Romaine lettuce, croutons, Parmesan cheese, and Caesar dressing.', category: 'Lunch' },
  { name: 'Eggs Benedict', price: 9.50, description: 'Poached eggs served atop English muffins with Canadian bacon and hollandaise sauce.', category: 'Breakfast' },
  { name: 'Apple Juice', price: 2.50, description: 'Sweet and tart apple juice.', category: 'Juice' },
  { name: 'Lemonade', price: 2.25, description: 'Refreshing lemonade made with freshly squeezed lemons.', category: 'Drinks' },
  { name: 'Latte', price: 4.00, description: 'Similar to a cappuccino, but with more milk and less foam.', category: 'Coffee' },
  { name: 'Tiramisu', price: 6.99, description: 'Italian dessert made with layers of coffee-soaked ladyfingers and mascarpone cheese.', category: 'Desserts' },
  { name: 'Chicken Quesadilla', price: 10.99, description: 'Grilled chicken and melted cheese folded in a flour tortilla.', category: 'Lunch' },
  { name: 'French Toast', price: 7.00, description: 'Slices of bread soaked in a mixture of eggs and milk, then fried.', category: 'Breakfast' },
  { name: 'Grape Juice', price: 2.50, description: 'Sweet and tangy grape juice.', category: 'Juice' },
  { name: 'Mojito', price: 8.50, description: 'Classic cocktail made with rum, mint, lime juice, sugar, and soda water.', category: 'Drinks' },
  { name: 'BLT Sandwich', price: 7.99, description: 'Classic sandwich with crispy bacon, fresh lettuce, and ripe tomatoes.', category: 'Lunch' },
  { name: 'Belgian Waffles', price: 8.99, description: 'Golden brown waffles served with whipped cream and berries.', category: 'Breakfast' },
  { name: 'Fruit Smoothie Bowl', price: 9.50, description: 'A bowl of blended fruit smoothie topped with granola, nuts, and fresh fruits.', category: 'Breakfast' },
  { name: 'Mango Tango Smoothie', price: 6.50, description: 'Refreshing smoothie made with fresh mangoes and tangy orange juice.', category: 'Drinks' },
  { name: 'Chicken Caesar Wrap', price: 9.99, description: 'Grilled chicken, romaine lettuce, Parmesan cheese, and Caesar dressing wrapped in a flour tortilla.', category: 'Lunch' },
  { name: 'Baguette with Brie', price: 10.50, description: 'Fresh baguette served with creamy Brie cheese and sliced apples.', category: 'Lunch' },
  { name: 'Avocado Toast', price: 6.99, description: 'Toasted bread topped with mashed avocado, cherry tomatoes, and a sprinkle of sea salt.', category: 'Breakfast' },
  { name: 'Mint Lemonade', price: 3.25, description: 'Refreshing lemonade infused with mint leaves.', category: 'Drinks' },
  { name: 'Mediterranean Salad', price: 9.50, description: 'Fresh salad with mixed greens, olives, feta cheese, cherry tomatoes, and balsamic vinaigrette.', category: 'Lunch' },
  { name: 'Coconut Water', price: 2.99, description: 'Natural coconut water served chilled.', category: 'Drinks' },
];

export default Data;
